site_name: End-to-End Open-source Collaboration Guidance 
# navigation
nav:
  - Introduction: index.md
  - Guidance: guidance.md
  - Meetings: meetings.md

# theme
theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    scheme: default # light mode
    primary: deep orange
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    #- navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - toc.follow
    - navigation.top
nav:
  - Home: 'index.md'
  - 'Why OS?': whyopensource.md
  - 'Using': 
    - 'Using OS': usingos.md
  - 'Releasing OS':
    - 'IP': 'releasingOS/ip.md'
    - 'Licences': releasingOS/licenses.md
    - 'Preparing': 'releasingOS/prep.md'
    - 'Reputational risks': releasingOS/reputation.md
    - 'Collaboration': releasingOS/collab.md
  - About:
    - 'Links': links.md
    - 'WG Team': 'team.md'
    - 'Meetings': 'meetings.md'
plugins:
  - search
  - git-revision-date
repo_url: https://github.com/phuse-org/E2E-OS-Guidance
repo_name: phuse-org/E2E-OS-Guidance
edit_uri: edit/main/docs/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - footnotes
#extra:
#  version:
#    provider: mike
